name: Publish to PyPi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Install Hatch
      uses: pypa/hatch@install
    - name: Update version
      run: |
        hatch version $(git describe --tags)
    - name: Build
      run: |
        hatch build
    - name: Publish to PyPi
      run: |
        hatch publish -n -u __token__ -a ${{ secrets.PYPI_API_TOKEN }}
